server:
  port: 0

spring:
  datasource:
    url: jdbc:mariadb://springboot-webservices-2022.cvokj1cptwnp.us-east-1.rds.amazonaws.com:3306/springboot_webservices_2022
    username: admin
    password: tlsRbqlqjs1!
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: false
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none

  profiles:
    include: oauth, real-db

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.31.86.214:8070/eureka/
