server:
  port: 8080
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.31.86.214:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
#      discovery.locator:
#        enabled: true # 수동매핑만 지원하려면 자동매핑 설정을 끄면 됨
#        lowerCaseServiceId: true
      routes:
      - id: organization-service # 선택적(optional) ID는 임의의 경로에 대한 ID
        uri: lb://organization-service # 이 경로의 대상 URI를 설정
        predicates: # 경로(path)는 load() 메서드로 설정되지만, 여러 옵션 중 하나
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        filters:
        - RewritePath=/license/(?<path>.*), /$\{path}
      - id: board-service
        uri: lb://board-service
        predicates:
        - Path=/board/**
        filters:
        - RewritePath=/board/(?<path>.*), /$\{path}
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
